Update shortcodes.csv
dasch-swiss/ark-resolver-data pull request #42
Opened 2022-01-25 06:11 UTC by danielasubotic

- Beyond the text
- Commode

2022-01-25 07:31 UTC, irinaschubert requested changes

2022-01-25 07:31 UTC, irinaschubert commented on data/shortcodes.csv
> +083B,commode,Canonicity, Obscenity, and the Making of Modern Chaucer (COMMode),
Ich glaube, es ist nicht erlaubt, mehr als 3 Kommas pro Zeile zu verwenden. Da es sich um ein CSV handelt, haben Kommas die Funktion, Datenfelder voneinander zu trennen.

2022-01-26 07:57 UTC, danielasubotic commented on data/shortcodes.csv
> +083B,commode,Canonicity, Obscenity, and the Making of Modern Chaucer (COMMode),
danke, habe es geändert

2022-01-26 07:57 UTC, irinaschubert approved these changes

2022-01-26 08:21 UTC, merged